openapi: 3.0.3
info:
  title: API Gateway CoAP para Sistema de Ascensores
  description: |
    API Gateway de puente CAN-CoAP para sistema de control de ascensores.
    
    Este API Gateway actúa como intermediario entre controladores CAN de ascensores 
    y el servidor central CoAP. NO es un servidor HTTP/REST, sino un puente de 
    protocolo que:
    
    - Recibe frames CAN de controladores de ascensores
    - Convierte a CoAP y envía al servidor central vía DTLS-PSK
    - Procesa respuestas del servidor central
    - Reenvía por CAN las asignaciones a los controladores
    
    Arquitectura del Sistema:
    Controladores CAN ↔ API Gateway ↔ Servidor Central CoAP
    
  version: 2.0.0
  contact:
    name: Sistema de Control de Ascensores

servers:
  - url: coap://192.168.49.2:5684
    description: Servidor Central (CoAP sobre DTLS-PSK)

paths:
  /peticion_piso:
    post:
      summary: Enviar una solicitud de llamada de ascensor desde un piso
      description: |
        Procesa una solicitud de llamada de ascensor desde un piso específico,
        enviando el estado actual de todos los ascensores gestionados.
        La solicitud se envía al servidor central a través de CoAP sobre DTLS-PSK.
        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FloorCallRequest'
      
      responses:
        '200':
          description: Respuesta exitosa del servidor central con la asignación del ascensor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
        '400':
          description: Error en la solicitud - JSON inválido, campos faltantes o piso fuera de rango.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: No autorizado - Sesión DTLS no establecida correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: Tipo de contenido no soportado - Se requiere application/json.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno en el servidor central durante procesamiento de solicitud.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /peticion_cabina:
    post:
      summary: Enviar una solicitud de destino desde la cabina de un ascensor
      description: |
        Procesa una solicitud de destino desde el interior de una cabina de ascensor,
        enviando el estado actual de todos los ascensores gestionados.
        La solicitud se envía al servidor central a través de CoAP sobre DTLS-PSK.
        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CabinRequest'
      
      responses:
        '200':
          description: Respuesta exitosa del servidor central con la asignación del ascensor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
        '400':
          description: Error en la solicitud - JSON inválido, campos faltantes o piso fuera de rango.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: No autorizado - Sesión DTLS no establecida correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: Tipo de contenido no soportado - Se requiere application/json.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno en el servidor central durante procesamiento de solicitud.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /llamada_emergencia:
    post:
      summary: Procesar llamadas de emergencia desde ascensores
      description: |
        Procesa solicitudes de emergencia originadas desde cabinas o controladores
        de ascensores. Activa protocolos de emergencia y notifica a servicios
        de mantenimiento y sistemas de seguridad.
        
        Tipos de emergencia soportados:
        - EMERGENCY_STOP: Botón de parada activado
        - POWER_FAILURE: Fallo de alimentación detectado
        - PEOPLE_TRAPPED: Personas atrapadas en cabina
        - MECHANICAL_FAILURE: Fallo mecánico del ascensor
        - FIRE_ALARM: Alarma de incendios activada
        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmergencyCallRequest'
      
      responses:
        '200':
          description: Solicitud de emergencia procesada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmergencyResponse'
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    DoorState:
      type: string
      enum: [CERRADA, ABIERTA, ABRIENDO, CERRANDO]
      description: |
        Estado actual de las puertas del ascensor:
        - CERRADA: Puertas completamente cerradas y bloqueadas
        - ABIERTA: Puertas completamente abiertas
        - ABRIENDO: Puertas en proceso de apertura
        - CERRANDO: Puertas en proceso de cierre
      example: CERRADA
      
    MovementDirection:
      type: string
      enum: [SUBIENDO, BAJANDO, PARADO]
      description: |
        Dirección de movimiento del ascensor:
        - SUBIENDO: Ascensor moviéndose hacia pisos superiores
        - BAJANDO: Ascensor moviéndose hacia pisos inferiores  
        - PARADO: Ascensor detenido en un piso
      example: SUBIENDO

    ElevatorState:
      type: object
      description: Estado completo de un ascensor individual.
      properties:
        id_ascensor:
          type: string
          description: Identificador único del ascensor (formato EdificioIDAnumero).
          pattern: '^E[0-9]+A[0-9]+$'
          example: E1A1
          maxLength: 23
        piso_actual:
          type: integer
          description: Piso actual del ascensor (0 = planta baja).
          minimum: 0
          maximum: 50
          example: 0
        estado_puerta:
          $ref: '#/components/schemas/DoorState'
        disponible:
          type: boolean
          description: Indica si el ascensor está disponible para nuevas tareas.
          example: true
        tarea_actual_id:
          type: string
          nullable: true
          description: ID de la tarea actual asignada por el servidor central.
          pattern: '^T_[0-9]+$'
          example: T_1640995200123
          maxLength: 31
        destino_actual:
          type: integer
          nullable: true
          description: Piso destino actual. Valor -1 o null indica sin destino asignado.
          minimum: -1
          maximum: 50
          example: null
      required:
        - id_ascensor
        - piso_actual
        - estado_puerta
        - disponible

    FloorCallRequest:
      type: object
      description: Solicitud de llamada de ascensor desde un piso.
      properties:
        id_edificio:
          type: string
          description: Identificador único del edificio.
          pattern: '^E[0-9]+$'
          example: E1
          maxLength: 23
        piso_origen_llamada:
          type: integer
          description: Piso desde donde se realiza la llamada.
          minimum: 0
          maximum: 50
          example: 2
        direccion_llamada:
          $ref: '#/components/schemas/MovementDirection'
        elevadores_estado:
          type: array
          items:
            $ref: '#/components/schemas/ElevatorState'
          description: Estado actual de todos los ascensores gestionados por el gateway.
          minItems: 1
          maxItems: 6
      required:
        - id_edificio
        - piso_origen_llamada
        - direccion_llamada
        - elevadores_estado

    CabinRequest:
      type: object
      description: Solicitud de destino desde la cabina de un ascensor.
      properties:
        id_edificio:
          type: string
          description: Identificador único del edificio.
          pattern: '^E[0-9]+$'
          example: E1
          maxLength: 23
        solicitando_ascensor_id:
          type: string
          description: Identificador del ascensor desde el cual se realiza la solicitud.
          pattern: '^E[0-9]+A[0-9]+$'
          example: E1A1
          maxLength: 23
        piso_destino_solicitud:
          type: integer
          description: Piso destino solicitado desde la cabina.
          minimum: 0
          maximum: 50
          example: 7
        elevadores_estado:
          type: array
          items:
            $ref: '#/components/schemas/ElevatorState'
          description: Estado actual de todos los ascensores gestionados por el gateway.
          minItems: 1
          maxItems: 6
      required:
        - id_edificio
        - solicitando_ascensor_id
        - piso_destino_solicitud
        - elevadores_estado

    ServerResponse:
      type: object
      description: Respuesta del servidor central con asignación de ascensor.
      properties:
        ascensor_asignado_id:
          type: string
          description: ID del ascensor asignado para la tarea.
          pattern: '^E[0-9]+A[0-9]+$'
          example: E1A1
          maxLength: 23
        tarea_id:
          type: string
          description: ID único de la tarea asignada por el servidor central.
          pattern: '^T_[0-9]+$'
          example: T_1640995200123
          maxLength: 31
        piso_destino_asignado:
          type: integer
          description: Piso destino asignado para esta tarea.
          minimum: 0
          maximum: 50
          example: 7
        tiempo_estimado_llegada:
          type: integer
          description: Tiempo estimado de llegada en segundos.
          minimum: 0
          maximum: 300
          example: 45
      required:
        - ascensor_asignado_id
        - tarea_id
        - piso_destino_asignado

    ErrorResponse:
      type: object
      description: Respuesta de error del servidor central.
      properties:
        error:
          type: string
          description: Tipo de error ocurrido.
          example: "Bad Request"
        message:
          type: string
          description: Mensaje descriptivo del error.
          example: "JSON inválido: campo 'piso_origen_llamada' es requerido"
        expected:
          type: string
          nullable: true
          description: Valor esperado (para errores de tipo de contenido).
          example: "application/json"
        received:
          type: integer
          nullable: true
          description: Valor recibido (para errores de tipo de contenido).
          example: 0
      required:
        - error
        - message

    EmergencyType:
      type: string
      enum: [EMERGENCY_STOP, POWER_FAILURE, PEOPLE_TRAPPED, MECHANICAL_FAILURE, FIRE_ALARM]
      description: |
        Tipos de emergencia que el sistema puede procesar
      example: PEOPLE_TRAPPED

    EmergencyCallRequest:
      type: object
      description: Solicitud de emergencia desde ascensor
      properties:
        id_edificio:
          type: string
          description: ID del edificio donde ocurre la emergencia
          pattern: '^E[0-9]+$'
          example: E1
          maxLength: 23
        ascensor_id_emergencia:
          type: string
          description: ID del ascensor que reporta la emergencia
          pattern: '^E[0-9]+A[0-9]+$'
          example: E1A1
          maxLength: 23
        tipo_emergencia:
          $ref: '#/components/schemas/EmergencyType'
        piso_actual_emergencia:
          type: integer
          description: Piso donde está el ascensor en emergencia
          minimum: 0
          maximum: 50
          example: 5
        descripcion_emergencia:
          type: string
          description: Descripción detallada de la emergencia
          maxLength: 500
          example: "Personas atrapadas, puerta no abre"
        timestamp_emergencia:
          type: string
          format: date-time
          description: Cuándo ocurrió la emergencia
          example: "2024-01-15T10:30:00Z"
        elevadores_estado:
          type: array
          items:
            $ref: '#/components/schemas/ElevatorState'
          description: Estado de todos los ascensores del edificio
          minItems: 1
          maxItems: 6
      required:
        - id_edificio
        - ascensor_id_emergencia
        - tipo_emergencia
        - piso_actual_emergencia
        - timestamp_emergencia
        - elevadores_estado

    EmergencyResponse:
      type: object
      description: Respuesta a una solicitud de emergencia
      properties:
        emergencia_id:
          type: string
          description: ID único generado para esta emergencia
          pattern: '^EMG_[0-9]+$'
          example: EMG_1640995200123
          maxLength: 31
        protocolo_activado:
          type: string
          description: Protocolo de emergencia que se activó
          enum: [RESCUE_PROTOCOL, MAINTENANCE_ALERT, FIRE_EVACUATION, POWER_BACKUP]
          example: RESCUE_PROTOCOL
        tiempo_respuesta_estimado:
          type: integer
          description: Tiempo estimado de respuesta en minutos
          minimum: 1
          maximum: 60
          example: 15
        servicios_notificados:
          type: array
          items:
            type: string
          description: Lista de servicios que fueron notificados
          example: ["BOMBEROS", "MANTENIMIENTO", "SEGURIDAD"]
        ascensores_redirection:
          type: array
          items:
            type: string
          description: Ascensores redirigidos para asistencia
          example: ["E1A2", "E1A3"]
      required:
        - emergencia_id
        - protocolo_activado
        - tiempo_respuesta_estimado
        - servicios_notificados 