apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: servidor-central-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servidor-central-deployment
  minReplicas: 1
  maxReplicas: 500
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70