apiVersion: v1
kind: Service
metadata:
  name: servidor-central-service
spec:
  selector:
    app: servidor-central
  ports:
  - protocol: UDP
    port: 5684
    targetPort: 5684
  type: LoadBalancer
  loadBalancerIP: 192.168.49.2